plugins:
  add_title_based_on_trust_level_enabled:
    default: false
    client: true
  tl0_title_on_create:
    default: ""
    type: string
  tl1_title_on_promotion:
    default: ""
    type: string
  tl2_title_on_promotion:
    default: ""
    type: string
  tl3_title_on_promotion:
    default: ""
    type: string
  tl4_title_on_promotion:
    default: ""
    type: string
  add_primary_group_title:
    default: false
    type: bool
  update_title_frequency:
    default: 24
    type: integer
  
